=head1 NAME

BScan::Utils - some useful command-line utilities

=head1 DESCRIPTION

 A Script For Getting Information on Hardware, Software and Atmospheres for Perl.

F<bscan> - print a date-time tag in form C<YYYY-MM-DD-hhmmss>


=head1 AUTHOR

BWC opensource@barca.com https://cloud.barca.com/

=head1 LICENSE

Perl License (perl)

=head1 INSTALLATION

Using C<cpan>:

 $ cpan BScan::Utils

Manual install:

 $ perl Makefile.PL
 $ make
 $ make install

=cut